apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: privacy
  namespace: argocd
  labels:
    vanillax.me: application
spec:
  generators:
    - git:
        repoURL: https://github.com/mitchross/k3s-argocd-proxmox
        revision: HEAD
        directories:
          - path: apps/privacy/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        vanillax.me: application
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: privacy
      source:
        repoURL: https://github.com/mitchross/k3s-argocd-proxmox
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        # Add these sync options for better PVC handling
        syncOptions:
          - PrunePropagationPolicy=foreground
          - PruneLast=true  # Ensures PVCs are deleted last
          - RespectIgnoreDifferences=true
