apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: privacy
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/mitchross/k3s-argocd-proxmox'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'searxng'
      server: '*'
    - namespace: 'proxitok'
      server: '*' 
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'