apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copyparty-data
  namespace: copyparty
  labels:
    app: copyparty
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
