apiVersion: v1
kind: ConfigMap
metadata:
  name: redlib-config
  namespace: redlib
data:
  REDLIB_PORT: "8080"
  REDLIB_ENABLE_RSS: "on"
  # Instance settings
  REDLIB_SFW_ONLY: "off"
  REDLIB_BANNER: "Welcome to Our Redlib Instance!"
  REDLIB_ROBOTS_DISABLE_INDEXING: "on"
  # Default user settings
  REDLIB_DEFAULT_THEME: "dark"
  REDLIB_DEFAULT_LAYOUT: "card"
  REDLIB_DEFAULT_WIDE: "on"
  REDLIB_DEFAULT_POST_SORT: "hot"
  REDLIB_DEFAULT_BLUR_NSFW: "on"
  REDLIB_DEFAULT_HIDE_AWARDS: "on"
  REDLIB_DEFAULT_FIXED_NAVBAR: "on"