apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: storage
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/mitchross/k3s-argocd-proxmox'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'openebs'
      server: '*'
    - namespace: 'csi-driver-nfs'
      server: '*'
    - namespace: 'csi-driver-smb'
      server: '*'
    - namespace: 'k8snative'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
