apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external
  namespace: gateway
spec:
  addresses:
  - type: IPAddress
    value: 192.168.10.22
  gatewayClassName: cilium
  listeners:
    - protocol: HTTP
      port: 80
      name: http-gateway
      hostname: "*.vanillax.xyz"
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTPS
      port: 443
      name: https-gateway
      hostname: "*.vanillax.xyz,vanillax.xyz"  # Combined hostnames
      tls:
        certificateRefs:
          - kind: Secret
            name: cert-vanillax
      allowedRoutes:
        namespaces:
          from: All