apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: gateway
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: 192.168.100.50
  listeners:
    - protocol: HTTPS
      port: 443
      name: https-gateway
      hostname: "*.vanillax.xyz"
      tls:
        certificateRefs:
          - kind: Secret
            name: cert-vanillax
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTPS
      port: 443
      name: https-domain-gateway
      hostname: "vanillax.xyz"
      tls:
        certificateRefs:
          - kind: Secret
            name: cert-vanillax
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTP
      port: 80
      name: http-gateway
      hostname: "*.vanillax.xyz"
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTP
      port: 80
      name: http-domain-gateway
      hostname: "vanillax.xyz"
      allowedRoutes:
        namespaces:
          from: All
