apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: gateway
  annotations:  
    io.cilium/lb-ipam-ips: "192.168.10.23"
    io.cilium/lb-force-ip: "true"
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: HTTPS
      port: 443
      name: https-gateway
      hostname: "*.vanillax.xyz"
      tls:
        certificateRefs:
          - kind: Secret
            name: cert-vanillax
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTPS
      port: 443
      name: https-domain-gateway
      hostname: "vanillax.xyz"
      tls:
        certificateRefs:
          - kind: Secret
            name: cert-vanillax
      allowedRoutes:
        namespaces:
          from: All
