apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - gateway-class.yaml
  - gw-external.yaml
  - gw-internal.yaml
  - cert-vanillax.yaml
