apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
    - git:
        repoURL: https://github.com/mitchross/k3s-argocd-starter.git
        revision: HEAD
        directories:
          - path: my-apps/*
          - exclude: true
            path: my-apps/applications-appset.yaml
  template:
    metadata:
      name: 'app-{{path.basename}}'
      labels:
        type: application
    spec:
      project: default
      source:
        repoURL: https://github.com/mitchross/k3s-argocd-starter.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: applications
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true