apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
helmCharts:
  - name: prometheus-blackbox-exporter
    repo: https://prometheus-community.github.io/helm-charts
    version: 10.1.0
    releaseName: blackbox-exporter
    valuesFile: values.yaml
resources:
  - probe.yaml
