apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-cluster-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Higher number means later sync
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: email
    privateKeySecretRef:
      name: cloudflare-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token