apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - cloudflare-external-secret.yaml
  - cluster-issuer.yaml


helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.16.2
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml


commonAnnotations:
  argocd.argoproj.io/sync-wave: "-10"