apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - cloudflare-secret.yaml
  - cluster-issuer.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.16.2
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml

replacements:
  - source:
      kind: Secret
      name: cloudflare-api-token
      fieldPath: data.email
    targets:
      - select:
          kind: ClusterIssuer
          name: cloudflare-cluster-issuer
        fieldPaths:
          - spec.acme.email
    options:
      decode: true

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-10"