apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - cloudflare-secret.yaml
  - cluster-issuer.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.16.2
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml

vars:
  - name: CLOUDFLARE_EMAIL
    objref:
      kind: Secret
      name: cloudflare-api-token
      apiVersion: v1
    fieldref:
      fieldpath: data.email

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-10"

namespace: cert-manager