apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - secret.yaml
  - redis.yaml

configMapGenerator:
  - name: searxng-config-settings
    files:
    - config/settings.yaml
    - config/limiter.toml
    options:
      disableNameSuffixHash: true

namespace: searxng