apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-config
  namespace: searxng
  labels:
    app: searxng
    type: config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath