apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openebs

resources:
  - namespace.yaml
  - storageclass.yaml

helmCharts:
  - name: openebs
    repo: https://openebs.github.io/charts
    version: 3.6.0
    releaseName: openebs
    namespace: openebs
    valuesFile: values.yaml

