apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openebs

resources:
  - namespace.yaml

helmCharts:
  - name: openebs
    repo: https://openebs.github.io/openebs
    version: 3.10.0
    releaseName: openebs
    namespace: openebs
    valuesFile: values.yaml

