apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openebs

resources:
  - namespace.yaml

helmCharts:
  - name: openebs
    repo: https://openebs.github.io/openebs  # New repo
    version: 4.1.0  # ✅ Latest version
    releaseName: openebs
    namespace: openebs
    valuesFile: values.yaml

