# Add the OpenEBS operator YAML manifests here
# You can obtain the manifests from the OpenEBS documentation or Helm chart
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openebs

resources:
  - namespace.yaml
  - localpv-storageclass.yaml
  
helmCharts:
  - name: openebs
    repo: https://openebs.github.io/charts
    releaseName: openebs
    namespace: openebs
    includeCRDs: true
    version: 3.10.0
    valuesFile: values.yaml

configMapGenerator:
  - name: openebs-values
    files:
      - values.yaml