apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-hostpath
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: "/var/openebs/local"
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

# OpenEBS LocalPV Provisioner
localprovisioner:
  enabled: true
  basePath: "/var/openebs/local/"
  hostpathClass:
    enabled: true
    isDefaultClass: false
    name: openebs-hostpath
    reclaimPolicy: Delete
    
# Disable other OpenEBS components we don't need
ndm:
  enabled: false
cstor:
  enabled: false
jiva:
  enabled: false
zfs-localpv:
  enabled: false 