# Enable only LocalPV provisioner
provisioner:
  enabled: true

# OpenEBS LocalPV Provisioner configuration
localprovisioner:
  enabled: true
  basePath: /var/openebs/local

# Disable other OpenEBS components we don't need
ndm:
  enabled: false
ndmOperator:
  enabled: false
cstor:
  enabled: false
jiva:
  enabled: false
zfs-localpv:
  enabled: false 