# infrastructure/storage/openebs/values.yaml
# Disable replicated storage for simple local PV setup
engines:
  replicated:
    enabled: false
    mayastor:
      enabled: false

# Enable local PV
localprovisioner:
  enabled: true
  basePath: "/var/openebs/local"

  hostpathClass:
    enabled: true
    isDefaultClass: false
    name: openebs-hostpath