{
 "title": "VictoriaMetrics - cluster",
 "description": "Overview for cluster VictoriaMetrics v1.29.0 or higher",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "job_insert",
    "query": "label_values(vm_app_version{version=~\"^vminsert.*\"}, job)"
   },
   {
    "name": "job_select",
    "query": "label_values(vm_app_version{version=~\"^vmselect.*\"}, job)"
   },
   {
    "name": "job_storage",
    "query": "label_values(vm_app_version{version=~\"^vmstorage.*\"}, job)"
   },
   {
    "name": "job",
    "query": "label_values(vm_app_version{version=~\"^vm.*\"}, job)"
   },
   {
    "name": "instance",
    "query": "label_values(vm_app_version{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Index size",
   "type": "singlestat",
   "description": "How many entries inverted index contains. This value is proportional to the number of unique timeseries in storage(cardinality).",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_rows{job=\"$job_storage\", type=\"indexdb\"})"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "singlestat",
   "description": "Total amount of used disk space",
   "gridPos": { "h": 2, "w": 9, "x": 8, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_data_size_bytes{job=\"$job_storage\", type!=\"indexdb\"})"
    }
   ]
  },
  {
   "title": "Total datapoints",
   "type": "singlestat",
   "description": "How many datapoints are in storage",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_rows{job=\"$job_storage\", type!=\"indexdb\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sort((time() - vm_app_start_timestamp{job=~\"$job\", instance=~\"$instance\"}) or (up{job=~\"$job\", instance=~\"$instance\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort(sum(up{job=~\"$job\", instance=~\"$instance\"}) by (job, instance))",
     "legendFormat": "{{instance}}({{job}})"
    }
   ]
  },
  {
   "title": "Datapoints ingestion rate ($instance)",
   "type": "graph",
   "description": "How many datapoints are inserted into storage per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_rows_inserted_total{job=~\"$job\", instance=~\"$instance\"}[5m])) by (type) > 0 ",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requests rate ($instance)",
   "type": "graph",
   "description": "* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_http_requests_total{job=~\"$job\", instance=~\"$instance.*\", path!~\"/favicon.ico\"}[5m])) by (path) > 0",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Churn rate ($instance)",
   "type": "graph",
   "description": "Shows how many of new time-series are created every second.  High churn rate tightly connected with database performance and may result in unexpected OOM's or slow queries. It is recommended to always keep an eye on this metric to avoid unexpected cardinality \"explosions\".\n\nGood references to read:\n* https://www.robustperception.io/cardinality-is-key\n* https://www.robustperception.io/using-tsdb-analyze-to-investigate-churn-and-cardinality",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_new_timeseries_created_total{job=~\"$job_storage\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "churn rate"
    }
   ]
  },
  {
   "title": "Query duration ($instance)",
   "type": "graph",
   "description": "The less time it takes is better.\n* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(vm_request_duration_seconds{job=~\"$job\", instance=~\"$instance\", quantile=~\"(0.5|0.99)\"}) by (path, quantile) > 0",
     "legendFormat": "{{quantile}} ({{path}})"
    }
   ]
  },
  {
   "title": "Requests error rate ($instance)",
   "type": "graph",
   "description": "* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_http_request_errors_total{job=~\"$job\", instance=~\"$instance.*\"}[5m])) by (path) > 0",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Active time series ($instance)",
   "type": "graph",
   "description": "Shows the number of active time series with new data points inserted during the last hour. High value may result in ingestion slowdown. \n\nSee following link for details:",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vm_cache_entries{job=~\"$job\", instance=~\"$instance.*\", type=\"storage/hour_metric_ids\"})",
     "legendFormat": "Active time series"
    }
   ]
  },
  {
   "title": "RPC errors ($instance)",
   "type": "graph",
   "description": "RPC errors are interconnection errors between cluster components. Errors rate should be 0 if network connection is stable and all components are up and operational.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_rpc_connection_errors_total{job=~\"$job\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "Connection"
    },
    {
     "expr": "sum(rate(vm_rpc_dial_errors_total{job=~\"$job\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "Dial"
    },
    {
     "expr": "sum(rate(vm_rpc_handshake_errors_total{job=~\"$job\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "Handshake"
    },
    {
     "expr": "sum(rate(vm_rpc_reroute_errors_total{job=~\"$job\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "Reroute"
    }
   ]
  },
  {
   "title": "Resource usage ($job)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU ($instance)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[5m])) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory usage ($instance)",
     "type": "graph",
     "description": "Amount of used memory (resident)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Goroutines ($instance)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(go_goroutines{job=~\"$job\", instance=~\"$instance\"}) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Threads ($instance)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_num_threads{job=~\"$job\", instance=~\"$instance\"}) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC duration ($instance)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(go_gc_duration_seconds{job=~\"$job\", instance=~\"$instance\", quantile=\"1\"}) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interconnection ($job)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rows ($instance)",
     "type": "graph",
     "description": "Shows number of pushed and sent rows. \n* `Pushed rows` - rows added to internal inserter buffers before send\n* `Sent rows` - successfully transmitted rows to storage nodes",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_rpc_rows_pushed_total{job=~\"$job\",instance=~\"$instance\"}[2m]))",
       "legendFormat": "Pushed"
      },
      {
       "expr": "sum(rate(vm_rpc_rows_sent_total{job=~\"$job\",instance=~\"$instance\"}[2m]))",
       "legendFormat": "Sent"
      }
     ]
    },
    {
     "title": "RPC errors ($instance)",
     "type": "graph",
     "description": "Rate of RPC errors by type:\n* `Connection` - the number of connection errors to vmstorage node\n* `Dial` -  the number of dial errors to vmstorage node.\n* `Handshake` - the number of handshake errors to vmstorage node\n* `Rerouted` - errors appeared during rerouting of rows from un-healthy storage node to a healthy one.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_rpc_connection_errors_total{job=~\"$job\",instance=~\"$instance\"}[5m]))",
       "legendFormat": "Connection"
      },
      {
       "expr": "sum(rate(vm_rpc_dial_errors_total{job=~\"$job\",instance=~\"$instance\"}[5m]))",
       "legendFormat": "Dial"
      },
      {
       "expr": "sum(rate(vm_rpc_handshake_errors_total{job=~\"$job\",instance=~\"$instance\"}[5m]))",
       "legendFormat": "Handshake"
      },
      {
       "expr": "sum(rate(vm_rpc_reroute_errors_total{job=~\"$job\",instance=~\"$instance\"}[5m]))",
       "legendFormat": "Reroute"
      }
     ]
    },
    {
     "title": "Rows ($instance) rerouted to ",
     "type": "graph",
     "description": "The number of rows rerouted to the vmstorage node from other nodes when they were unhealthy.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_rpc_rows_rerouted_to_here_total{job=~\"$job\", instance=~\"$instance\"}[5m])) by(addr) > 0",
       "legendFormat": "{{addr}}"
      }
     ]
    },
    {
     "title": "Rows ($instance) rerouted from",
     "type": "graph",
     "description": "The number of rows rerouted from the vmstorage node to healthy nodes when the given node was unhealthy.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_rpc_rows_rerouted_from_here_total{job=~\"$job\", instance=~\"$instance\"}[5m])) by(addr) > 0",
       "legendFormat": "{{addr}}"
      }
     ]
    },
    {
     "title": "Pending",
     "type": "graph",
     "description": "The number of rows or bytes that vminesrt internal buffer contains at the moment.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vm_rpc_buf_pending_bytes{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "bytes"
      },
      {
       "expr": "sum(vm_rpc_rows_pending{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "rows"
      }
     ]
    },
    {
     "title": "Rows lost  ($instance)",
     "type": "graph",
     "description": "The number of rows that were lost because of unhealthy vmstorage nodes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_rpc_rows_lost_total{job=~\"$job\", instance=~\"$instance\"}[5m]))",
       "legendFormat": "rows"
      }
     ]
    },
    {
     "title": "RPC network usage ($instance)",
     "type": "graph",
     "description": "Network usage by internal VictoriaMetrics RPC protocol",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_tcpdialer_written_bytes_total{job=~\"$job\", instance=~\"$instance\"}[5m]))",
       "legendFormat": "network usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Caches ($job)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache size ($instance)",
     "type": "graph",
     "description": "VictoriaMetrics stores various caches in RAM. Memory size for these caches may be limited with -`memory.allowedPercent` flag. Line `max allowed` shows max allowed memory size for cache.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(vm_cache_size_bytes{job=~\"$job\", instance=~\"$instance\"}) by(type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(vm_allowed_memory_bytes{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "max allowed"
      }
     ]
    },
    {
     "title": "Cache hit ratio ($instance)",
     "type": "graph",
     "description": "VictoriaMetrics stores various caches in RAM. Memory size for these caches may be limited with -`memory.allowedPercent` flag. Line `max allowed` shows max allowed memory size for cache.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - (sum(rate(vm_cache_misses_total{job=~\"$job\", instance=~\"$instance\"}[5m])) by (type) / sum(rate(vm_cache_requests_total{job=~\"$job\", instance=~\"$instance\"}[5m])) by (type))",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "storage ($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Datapoints ($instance)",
     "type": "graph",
     "description": "How many datapoints are in the storage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vm_rows{job=\"$job_storage\", instance=~\"$instance\", type != \"indexdb\"}) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Ingestion rate ($instance)",
     "type": "graph",
     "description": "Shows how many rows per second every storage node accepts. This metric doesn't show all stored rows since some of them may be dropped because of wrong timestamps or decode errors.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_vminsert_metrics_read_total{job=\"$job_storage\", instance=~\"$instance\"}[5m])) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk space usage (index)  ($instance)",
     "type": "graph",
     "description": "Shows amount of on-disk space occupied by inverted index.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(vm_data_size_bytes{job=\"$job_storage\", instance=~\"$instance\", type=\"indexdb\"}) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk space usage (datapoints) ($instance)",
     "type": "graph",
     "description": "Shows amount of on-disk space occupied by data points.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(vm_data_size_bytes{job=\"$job_storage\", instance=~\"$instance\", type!=\"indexdb\"}) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Active merges ($instance)",
     "type": "graph",
     "description": "The number of on-going merges in storage nodes.  It is expected to have high numbers for `storage/small` metric.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vm_active_merges{job=\"$job_storage\", instance=~\"$instance\"}) by(type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Pending datapoints ($instance)",
     "type": "graph",
     "description": "How many datapoints are in RAM queue waiting to be written into storage. The less is better.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vm_pending_rows{job=\"$job_storage\", instance=~\"$instance\", type=\"storage\"})",
       "legendFormat": "pending datapoints"
      },
      {
       "expr": "sum(vm_pending_rows{job=\"$job_storage\", instance=~\"$instance\", type=\"indexdb\"})",
       "legendFormat": "pending index entries"
      }
     ]
    },
    {
     "title": "LSM parts ($instance)",
     "type": "graph",
     "description": "Data parts of LSM tree.\nHigh number of parts could be an evidence of slow merge performance - check the resource utilization.\n* `indexdb` - inverted index\n* `storage/small` - recently added parts of data ingested into storage(hot data)\n* `storage/big` -  small parts gradually merged into big parts (cold data)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vm_parts{job=\"$job_storage\", instance=~\"$instance\"}) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Merge speed",
     "type": "graph",
     "description": "The number of rows merged per second by storage nodes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_rows_merged_total{job=\"$job_storage\", instance=~\"$instance\"}[5m])) by(type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Concurrent inserts ($instance)",
     "type": "graph",
     "description": "Shows how many ongoing insertions are taking place.\n* `max` - equal to number of CPU * 2\n* `current` - current number of goroutines busy with inserting rows into storage\n\nWhen `current` hits `max` constantly, it means storage is overloaded and require more CPU.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vm_concurrent_addrows_capacity{job=\"$job_storage\", instance=~\"$instance\"})",
       "legendFormat": "max"
      },
      {
       "expr": "sum(vm_concurrent_addrows_current{job=\"$job_storage\", instance=~\"$instance\"})",
       "legendFormat": "current"
      }
     ]
    }
   ]
  },
  {
   "title": "vmselect ($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests rate ($instance)",
     "type": "graph",
     "description": "Request rate accepted by vmselect nodes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_http_requests_total{job=~\"$job_select\", instance=~\"$instance.*\", path!~\"/favicon.ico\"}[5m])) by (path) > 0",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Concurrent selects ($instance)",
     "type": "graph",
     "description": "Shows how many ongoing insertions are taking place.\n* `max` - equal to number of CPU * 2 by default. May be configured with `search.maxConcurrentRequests` flag\n* `current` - current number of goroutines busy with processing requests\n\nWhen `current` hits `max` constantly, it means vmselect node is overloaded and require more CPU or higher limits.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vm_concurrent_queries{job=\"$job_select\", instance=~\"$instance\"})",
       "legendFormat": "max"
      },
      {
       "expr": "sum(vm_concurrent_select_capacity{job=\"$job_select\", instance=~\"$instance\"})",
       "legendFormat": "current"
      }
     ]
    },
    {
     "title": "Network usage ($instance)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_tcplistener_read_bytes_total{job=~\"$job_select\", instance=~\"$instance\"}[5m])) by (instance) > 0",
       "legendFormat": "read - {{instance}}"
      },
      {
       "expr": "sum(rate(vm_tcplistener_written_bytes_total{job=~\"$job_select\", instance=~\"$instance\"}[5m])) by (instance) > 0",
       "legendFormat": "write - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "vminsert ($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests rate ($instance)",
     "type": "graph",
     "description": "* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_http_requests_total{job=~\"$job_insert\", instance=~\"$instance.*\", path!~\"/favicon.ico\"}[5m])) by (path) > 0",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Concurrent inserts ($instance)",
     "type": "graph",
     "description": "Shows how many ongoing insertions are taking place.\n* `max` - equal to number of CPU * 4 by default. May be configured with `maxConcurrentInserts` flag\n* `current` - current number of goroutines busy with processing requests\n\nWhen `current` hits `max` constantly, it means vminsert node is overloaded and require more CPU or higher limits.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vm_concurrent_insert_current{job=\"$job_insert\", instance=~\"$instance\"})",
       "legendFormat": "max"
      },
      {
       "expr": "sum(vm_concurrent_insert_capacity{job=\"$job_insert\", instance=~\"$instance\"})",
       "legendFormat": "current"
      }
     ]
    },
    {
     "title": "Network usage ($instance)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_tcplistener_read_bytes_total{job=~\"$job_insert\", instance=~\"$instance\"}[5m])) by (instance) > 0",
       "legendFormat": "read - {{instance}}"
      },
      {
       "expr": "sum(rate(vm_tcplistener_written_bytes_total{job=~\"$job_insert\", instance=~\"$instance\"}[5m])) by (instance) > 0",
       "legendFormat": "write - {{instance}}"
      }
     ]
    },
    {
     "title": "Rows per insert ($instance)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vm_rows_per_insert{job=~\"$job\", instance=~\"$instance\", quantile=\"0.99\"}) by (instance) > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}