apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - thanos-route.yaml
  - thanos-object-storage-secret.yaml
helmCharts:
  - name: thanos
    repo: https://charts.bitnami.com/bitnami
    version: 16.0.7
    releaseName: thanos
    namespace: monitoring
    valuesFile: values.yaml
