apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: monitoring
type: Opaque
data:
  objstore.yml: dHlwZTogUzMKY29uZmlnOgogIGJ1Y2tldDogdGhhbm9zCiAgZW5kcG9pbnQ6IG1pbmlvLm1vbml0b3Jpbmcuc3ZjLmNsdXN0ZXIubG9jYWw6OTAwMAogIGFjY2Vzc19rZXk6IG1pbmlvYWRtaW4KICBzZWNyZXRfa2V5OiBtaW5pb2FkbWluCiAgaW5zZWN1cmU6IHRydWUKICBzaWduYXR1cmVfdmVyc2lvbjogdjQKICBodHRwX2NvbmZpZzoKICAgIGlkbGVfY29ubl90aW1lb3V0OiA5MHMKICAgIHJlc3BvbnNlX2hlYWRlcl90aW1lb3V0OiAycwogICAgaW5zZWN1cmVfc2tpcF92ZXJpZnk6IHRydWU=
