apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: libreddit
spec:
  parentRefs:
  - name: gateway
  hostnames:
  - "libreddit.example.com"
  rules:
  - matches:
    - path:
        type: Prefix
        value: /
    backendRefs:
    - name: libreddit
      port: 8080
