apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  cidrs:
    - cidr: "192.168.10.20/28"  # 192.168.10.16-31 (16 IPs)
  serviceSelector:
    matchExpressions:
      - key: app-type
        operator: In
        values: ["gateway", "internal-service"]