apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: home-pool
spec:
  cidrs:
    - cidr: "192.168.10.20/29"  # Covers 192.168.10.20-27 (8 IPs)
    - cidr: "192.168.10.28/31"  # Covers 192.168.10.28-29 (2 IPs)
  disable: false