apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: home-lab-pool
spec:
  cidrs:
    - cidr: "192.168.10.20/29"  # 20-27
    - cidr: "192.168.10.28/30"  # 28-29
  disable: false
  # Allow services to request specific IPs
  serviceSelector:
    matchExpressions:
      - key: app
        operator: Exists