cluster:
  name: nuc
  id: 1
kubeProxyReplacement: true
enableEnvoyConfig: true
# DNS Configuration
enableRemoteNodeIdentity: true
routingMode: "native"
ipv4NativeRoutingCIDR: "10.0.0.0/8"
bpf:
  masquerade: true
k8s:
  requireIPv4PodCIDR: true
# Metrics and Monitoring configuration
prometheus:
  enabled: true
  serviceMonitor:
    enabled: false
    trustCRDsExist: true
  contextPath: /metrics
  metrics:
    - dns:query
    - drop
    - tcp
    - flow
    - port-distribution
    - icmp
    - http
# Debug configuration
debug:
  enabled: true
  verbose: "true"
# Talos specific
k8sServiceHost: 192.168.10.202
k8sServicePort: 6443
securityContext:
  capabilities:
    ciliumAgent: [CHOWN, KILL, NET_ADMIN, NET_RAW, IPC_LOCK, SYS_ADMIN, SYS_RESOURCE, DAC_OVERRIDE, FOWNER, SETGID, SETUID]
    cleanCiliumState: [NET_ADMIN, SYS_ADMIN, SYS_RESOURCE]
operator:
  replicas: 1
  rollOutPods: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: false
    port: 9963
  resources:
    limits:
      cpu: 800m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
# Hubble Configuration
hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - icmp
      - http
    serviceMonitor:
      enabled: false
  relay:
    enabled: true
    rollOutPods: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: false
  ui:
    enabled: true
    rollOutPods: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: false
# Envoy Configuration
envoy:
  enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: false
  accessLog: "/dev/stdout"
  concurrency: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  proxy:
    idleTimeout: 60s
    connectTimeout: 30s
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy: [NET_ADMIN, SYS_ADMIN, NET_BIND_SERVICE, PERFMON, BPF]
# IPAM Configuration
ipam:
  mode: kubernetes
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
rollOutCiliumPods: true
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi
k8sClientRateLimit:
  qps: 20
  burst: 100
l2announcements:
  enabled: true
externalIPs:
  enabled: true
enableCiliumEndpointSlice: true
loadBalancer:
  algorithm: maglev
# Gateway API Configuration
gatewayAPI:
  enabled: true
  secretsNamespace:
    create: false
    name: gateway
  controller: true
ingressController:
  enabled: false
  default: true
  loadbalancerMode: shared
  service:
    annotations:
      io.cilium/lb-ipam-ips: 192.168.10.21
