cluster:
  name: vanillax-cluster
  id: 1

kubeProxyReplacement: true
 
ipam:
  mode: kubernetes

l2announcements:
  enabled: true
  interface: eth0
  leaseDuration: 10s

gatewayAPI:
  enabled: true
  hostNetwork:
    enabled: false

envoy:
  enabled: true
  socketPath: /var/run/cilium/envoy/sockets
  securityContext:
    privileged: true
    capabilities:
      keepCapNetBindService: true
      add: [NET_ADMIN, PERFMON, BPF, SYS_ADMIN]

volumes:
  - name: envoy-sock-dir
    hostPath:
      path: /var/run/cilium/envoy/sockets
      type: DirectoryOrCreate

volumeMounts:
  - name: envoy-sock-dir
    mountPath: /var/run/cilium/envoy/sockets

operator:
  replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"