apiVersion: apps/v1
kind: Deployment
metadata:
  name: libreddit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libreddit
  template:
    metadata:
      labels:
        app: libreddit
    spec:
      containers:
      - name: libreddit
        image: spikecodes/libreddit:latest
        ports:
        - containerPort: 8080
