apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflared

resources:
  - ns.yaml
  - daemon-set.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: config
    files:
      - config.yaml
    options:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"

# The secret will be created manually via kubectl
# ... existing code ...
  