apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-controller
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: argocd
        path: infrastructure/controllers/argocd
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/mitchross/k3s-argocd-starter.git
        targetRevision: HEAD
        path: '{{path}}'
        plugin:
          name: kustomize-with-helm 
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true