apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: networking
        path: infrastructure/networking
      - name: storage
        path: infrastructure/storage
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/mitchross/k3s-argocd-starter.git
        targetRevision: HEAD
        path: '{{path}}'
        plugin:
          name: kustomize-with-helm
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true