apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-components
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/mitchross/k3s-argocd-starter.git
      revision: HEAD
      directories:
      - path: infrastructure/networking/*
      - path: infrastructure/storage/*
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/mitchross/k3s-argocd-starter.git
        targetRevision: HEAD
        path: '{{path}}'
        plugin:
          name: kustomize-build-with-helm
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      # Override namespace for special cases
      ignoreDifferences:
      - group: "*"
        kind: "*"
        jsonPointers:
        - /metadata/namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=false  # Don't auto-create namespaces 