apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  configManagementPlugins: |
    - name: kustomize-with-helm
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm repo add cilium https://helm.cilium.io"]
      generate:
        command: ["/bin/sh", "-c"]
        args: ["kustomize build --enable-helm"]