apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-localpv
parameters:
  storageType: hostpath
  basePath: /var/openebs/local
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
